name: Nix Config Lint
on:
  push:
    branches:
      - main
    paths:
      - '*.nix'
      - 'dotfiles/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
          # - name: Install linters
          #   run: |
          #     nix-env -iA nixpkgs.luacheck
          #     nix-env -iA nixpkgs.emacs
          #     nix-env -iA nixpkgs.nodePackages.jsonlint
          #     nix-env -iA nixpkgs.fish
          #     nix-env -iA nixpkgs.shellcheck

      - name: Evaluate Nix configurations
        run: |
          nix-instantiate --eval configuration.nix dotfiles/*.nix

          # - name: Extract and lint Lua code (Wezterm)
          #   run: |
          #     nix eval --raw -f wezterm.nix 'config.home-manager.users.blank.home.file.".config/wezterm/wezterm.lua".text' > extracted_wezterm.lua
          #     luacheck extracted_wezterm.lua

          # - name: Extract and lint Emacs Lisp code (Doom)
          #   run: |
          #     nix eval --raw -f doom.nix 'config.home-manager.users.blank.home.file.".config/doom/config.el".text' > extracted_doom_config.el
          #     nix eval --raw -f doom.nix 'config.home-manager.users.blank.home.file.".config/doom/init.el".text' > extracted_doom_init.el
          #     emacs --batch -f batch-byte-compile extracted_doom_config.el extracted_doom_init.el

          # - name: Extract and lint TOML (Starship)
          #   run: |
          #     nix eval --raw -f starship.nix 'config.home-manager.users.blank.home.file.".config/starship.toml".text' > extracted_starship.toml
          #     jsonlint -q extracted_starship.toml

          # - name: Extract and lint Fish scripts
          #   run: |
          #     nix eval --raw -f fish.nix 'config.home-manager.users.blank.home.file.".config/fish/config.fish".text' > extracted_fish_config.fish
          #     nix eval --raw -f fish.nix 'config.home-manager.users.blank.home.file.".config/fish/conf.d/aliases.fish".text' > extracted_fish_aliases.fish
          #     fish -n extracted_fish_config.fish
          #     fish -n extracted_fish_aliases.fish

          # - name: Extract and lint TOML (Yazi)
          #   run: |
          #     nix eval --raw -f yazi.nix 'config.home-manager.users.blank.home.file.".config/yazi/yazi.toml".text' > extracted_yazi.toml
          #     jsonlint -q extracted_yazi.toml
