name: Nix Config Lint
on:
  push:
    branches:
      - main
    paths:
      - '*.nix'
      - 'dotfiles/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Evaluate Nix configurations
        run: |
          nix-instantiate --eval configuration.nix dotfiles/*.nix

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract content from Nix files
        run: |
          python3 - <<EOF
          import os
          import re

          def extract_content(file_path):
              with open(file_path, 'r') as f:
                  content = f.read()
              
              # Updated regex pattern to capture content correctly
              pattern = r'"([^"]+)".text\s*=\s*\'\'\s*([\s\S]*?)\'\'\s*;\s*'
              matches = re.findall(pattern, content, re.DOTALL)
              
              for file_path, file_content in matches:
                  file_name = os.path.basename(file_path)
                  full_path = os.path.join('extracted_files', file_name)
                  with open(full_path, 'w') as f:
                      f.write(file_content.strip())  # Strip leading/trailing whitespace

          os.makedirs('extracted_files', exist_ok=True)
          for root, dirs, files in os.walk('dotfiles'):
              for file in files:
                  if file.endswith('.nix') and file != 'neovim.nix':
                      extract_content(os.path.join(root, file))
          EOF

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Fish Shell and Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y fish emacs

      - name: Install linters
        run: |
          npm install -g luacheck @panekj/lib

      - name: Lint Fish files
        run: |
          echo "Linting Fish files..."
          for file in extracted_files/*.fish; do
            fish -n "$file"
          done

      - name: Lint Emacs Lisp files
        run: |
          echo "Linting Emacs Lisp files..."
          for file in extracted_files/*.el; do
            emacs --batch -f batch-byte-compile "$file" || echo "Linting failed for $file"
          done

      - name: Lint TOML files
        run: |
          echo "Linting TOML files..."
          for file in extracted_files/*.toml; do
            taplo check "$file"
          done

      - name: Lint Lua files
        run: |
          echo "Linting Lua files..."
          luacheck extracted_files/*.lua
