name: Nix Config Lint
on:
  push:
    branches:
      - main
    paths:
      - '*.nix'
      - 'dotfiles/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Evaluate Nix configurations
        run: |
          nix-instantiate --eval configuration.nix dotfiles/*.nix

      - name: Extract content from Nix files
        run: |
          mkdir -p extracted_files
          for file in dotfiles/*.nix; do
            filename=$(basename "$file" .nix)
            nix eval --raw -f "$file" 'config.home-manager.users.blank.home.file' | 
            jq -r 'to_entries[] | select(.key | endswith(".text")) | 
            .key[1:-6] as $path | 
            .value | 
            @sh "mkdir -p extracted_files/$(dirname \($path)) && 
            echo \(.) > extracted_files/\($path)"' | 
            sh
          done

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: extracted_files/.*
